### ISSUE TITLE
fatalError

### ISSUE THREAD

**Issue by GalKeidar10** [enmiller/ENMBadgedBarButtonItem-Swift#23]
Getting the error: `fatalError("init(coder:) has not been implemented.  This UIBarButtonItem requires a custom view in order to use.  Please use the designated initializer -init(customView:value:)")`

Implemented using Interface Builder.
What does this mean: `Please use the designated initializer -init(customView:value:)`?

**Comment by ikudriavtsev** [comment]
If you installed this project using pod more likely you didn't get the most recent version of it. Check in your Podfile.lock, the latest version is 3.0.1 - at least according to the tags available at this repo.
You need to specify the version explicitly:
`pod 'ENMBadgedBarButtonItem', '~> 3.0.1'`
I don't think this is a proper fix, however as a workaround it's ok in my opinion.

**Comment by enmiller** [comment]
Closing this issue due to the storyboard instantiation being addressed in v3.0.0.

@GalKeidar10 The latest release, `v4.0.0`, should resolve this error you are seeing.  If you want to use the minimum required version to resolve the error, you can use `v3.0.1`.  I'd recommend using the most recent version though.
